import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { auth } from '../app/firebaseApp'
import { useRouter } from 'next/router'

import { useAuthState } from 'react-firebase-hooks/auth'

import Loading from '../components/elements/Loading'
import Error from '../components/elements/Error'

/*
Nothing is here yet
server side generated:
    -client checks login status
    -server access cookies
*/

export default function Home() {
  const [user, loading, error] = useAuthState(auth)
  const router = useRouter();
  const handleSignOut = () => {
    auth.signOut()
    router.push('/login')
  }

  if (loading) return <Loading />
  else if (error) return <Error msg={error.message} />

  else if (user) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Main</h1>
        <button onClick={handleSignOut}>Sign Out</button>
      </div>
    )
  }

  router.push('/login');
  return <h1>Redirecting...</h1>
}
