import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { auth } from '../app/firebaseApp';
import { useRouter } from 'next/router';


/*
server side generated:
    -client checks login status
    -server access cookies
*/

export default function Home() {
  const router = useRouter();
  const handleSignOut = () => {
    auth.signOut()
    router.push('/login')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Main</h1>
      <button onClick={handleSignOut}>Sign Out</button>
    </div>
  )
}
